### ISSUE TITLE
Is this stil being updated?

### ISSUE THREAD

**Issue by LordMZTE** [osum4est/the-bom-plugin#12]
i hope this mod is still being worked on because its so useful and there is no other mod like that out there for 1.12.2

**Comment by Dimentive** [comment]
The mod no longer works, and it seems to have been abandoned. That’s a shame.

**Comment by a5161655** [comment]
That’s a shame.

**Comment by Dimentive** [comment]
That’s a shame.

**Comment by FancyFurret** [comment]
Sorry guys, I only really work on mods when I'm into Minecraft, but i've been playing it lately and figured i'd come and work on my mod some more. Hopefully i'll have an update fixing these issues out relatively soon!

**Comment by Dimentive** [comment]
That’s a shame.

**Comment by Dimentive** [comment]
That’s a shame.

Jokes aside, thanks for the reply! One can’t be expected to care for the same game non-stop, so don’t worry about it.

Still, I hope you’ll make an update that makes the mod work again, as it’s such a useful mod. It would make a lot of people very happy. 😃

**Comment by a5161655** [comment]
thanks for your update(beforehand)
