### ISSUE TITLE
Lag Spikes when showing a "recipes" with many items.

### ISSUE THREAD

**Issue by Fundryi** [osum4est/the-bom-plugin#2]
Title describes it pretty much, I just want to report this maybe you can do something against it but my guess is not really, i mean it has to calculate everything soooo :P

Lag Spikes holds for 2 Seconds
The recipe I tested with:
https://i.gyazo.com/50b33f59e92575f246ee62be8a6daaa1.mp4
You can see it's freezing for some seconds.

Regards, Fundryi

**Comment by FancyFurret** [comment]
Thanks for the feedback! Optimization is one thing that I definitely need to improve. At the very least I can add a cache so that it will only lag the first time it calculates the recipe.

If possible, could you give me the specs for your computer,  as well as the pack you are playing with/number of mods?

**Comment by Fundryi** [comment]
Yes of course.

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Core i7 6800K @ 3.40GHz
	Broadwell-E/EP 14nm Technology
RAM
	32,0GB Unknown @ 1199MHz (15-15-15-35)
Motherboard
	MSI X99A GAMING PRO CARBON (MS-7A20) (SOCKET 0)
Graphics
	ROG PG279Q (2560x1440@165Hz)
	MD 20144 (1920x1080@60Hz)
	32W_LCD_TV (1804x1014@60Hz)
	4095MB NVIDIA GeForce GTX 1080 (Gigabyte) < ITS 8 GB IDK WHY IT DOSE IT
Storage
	238GB SAMSUNG MZVLW256HEHP-00000 (SSD)
	463GB Microsoft Storage Space Device (SSD)
	1853GB Microsoft Storage Space Device (HDD)

**Comment by Fundryi** [comment]
Mod List: http://www.modlister.com/user/Noplix/Destiny%201.12

**Comment by FancyFurret** [comment]
That's a crazy recipe! Adding a cache should help, and I may be able to make some optimizations. I've also realized I'll need to add mystical agriculture essence to my blacklist. Working on it!

**Comment by Fundryi** [comment]
Will the cache hold until next restart or will it be resisted :)? I mean would be helpful with really big recipes.

**Comment by FancyFurret** [comment]
It will not hold, but the way I'm implementing the cache makes is so that the even the first run pretty much instantaneous! Basically it caches each recipe as it goes, so 1k drive is only calculated once, then the 4k, and so on. This dramatically speeds things up

**Comment by FancyFurret** [comment]
Implemented in latest commit. Will release new version soon, after I make a few other fixes

**Comment by Fundryi** [comment]
I know it's closed but u should also add UU-Matter from TechReborn to the black list. Just and idea :P

**Comment by FancyFurret** [comment]
I did add it! Just pushed a new version to curse, it's processing now but should be done soon. I've also added a config file where you can add your own blacklist items!

**Comment by Fundryi** [comment]
Sound cool! can't wait :)
