### ISSUE TITLE
Port to older versions

### ISSUE THREAD

**Issue by KewaiiGamer** [osum4est/the-bom-plugin#3]
I always wanted to have a mod like mainly because it helps me keeping track of my resources and if I can or can't craft something however I play mainly on 1.7.10. Perhaps you could port it to 1.17.10 with NEI integration  instead and to 1.10.2 and 1.11.2 too. 

Great job btw :D

**Comment by FancyFurret** [comment]
Sorry, this mod will only be for 1.12 and onwards. If you are playing on 1.7.10 you could take a look at [CraftingCosts](https://mods.curse.com/mc-mods/minecraft/224427-craftingcosts), which is similar.
